[2023-04-23T05:52:17.264+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: notifier_hourly.Check_threshold scheduled__2023-04-22T18:00:00+00:00 [queued]>
[2023-04-23T05:52:17.371+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: notifier_hourly.Check_threshold scheduled__2023-04-22T18:00:00+00:00 [queued]>
[2023-04-23T05:52:17.372+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T05:52:17.372+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2023-04-23T05:52:17.372+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T05:52:17.547+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): Check_threshold> on 2023-04-22 18:00:00+00:00
[2023-04-23T05:52:17.571+0000] {standard_task_runner.py:55} INFO - Started process 802 to run task
[2023-04-23T05:52:17.589+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'notifier_hourly', 'Check_threshold', 'scheduled__2023-04-22T18:00:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/notifierdag.py', '--cfg-path', '/tmp/tmpt6cq016b']
[2023-04-23T05:52:17.592+0000] {standard_task_runner.py:83} INFO - Job 54: Subtask Check_threshold
[2023-04-23T05:52:17.877+0000] {task_command.py:389} INFO - Running <TaskInstance: notifier_hourly.Check_threshold scheduled__2023-04-22T18:00:00+00:00 [running]> on host 030724a7a4e3
[2023-04-23T05:52:18.369+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=notifier_hourly
AIRFLOW_CTX_TASK_ID=Check_threshold
AIRFLOW_CTX_EXECUTION_DATE=2023-04-22T18:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-22T18:00:00+00:00
[2023-04-23T05:52:18.389+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/project/controller.py", line 51, in check_threshold
    df = pd.read_csv(file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 69, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 549, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
[2023-04-23T05:52:18.437+0000] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=notifier_hourly, task_id=Check_threshold, execution_date=20230422T180000, start_date=20230423T055217, end_date=20230423T055218
[2023-04-23T05:52:18.659+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 54 for task Check_threshold (No columns to parse from file; 802)
[2023-04-23T05:52:18.730+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-23T05:52:18.800+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
